services:
  - type: web
    name: flight-scraper
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python flight_scraper.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: YOUR_BOT_TOKEN_HERE
      - key: TELEGRAM_CHAT_ID
        value: YOUR_CHAT_ID_HERE

  - type: cron
    name: flight-scraper-cron
    runtime: python3
    buildCommand: pip install -r requirements.txt
    schedule: "0 6,10,14,18,22 * * *"
    startCommand: python flight_scraper.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: YOUR_BOT_TOKEN_HERE
      - key: TELEGRAM_CHAT_ID
        value: YOUR_CHAT_ID_HERE
